# Generated by Django 2.1.2 on 2018-10-02 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('camera_type', models.IntegerField(choices=[(0, 'nie pamiętam'), (1, 'inny'), (2, 'wielkoformatowy'), (3, 'średnioformatowy'), (4, 'mały obrazek'), (5, 'wielkoformatowy')], default=0)),
                ('camera_name', models.IntegerField(choices=[(0, 'nie pamiętam'), (1, 'inny'), (2, 'Canon')], default=0)),
                ('film_type', models.IntegerField(choices=[(2, 'Canon'), (0, 'nie pamiętam'), (1, 'inny')], default=0)),
                ('film_name', models.IntegerField(choices=[(3, 'Foma'), (4, 'Fuji'), (1, 'inny'), (5, 'Kodak'), (2, 'Ilford'), (0, 'nie pamiętam')], default=0)),
                ('film_iso', models.IntegerField(choices=[(3, '200'), (2, '100'), (1, 'inny'), (4, '400'), (5, '800'), (7, '3200'), (0, 'nie pamiętam'), (6, '1000')], default=0)),
                ('film_options', models.BooleanField(default=False)),
                ('description', models.TextField(null=True)),
                ('photo_options', models.BooleanField(default=False)),
                ('favourite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SilverFox.User'),
        ),
    ]
