# Generated by Django 2.1.2 on 2018-10-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SilverFox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='camera_type',
            field=models.IntegerField(choices=[(0, 'nie pamiętam'), (1, 'inny'), (2, 'wielkoformatowy'), (3, 'średnioformatowy'), (4, 'mały obrazek')], default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='film_iso',
            field=models.IntegerField(choices=[(2, '25'), (0, 'nie pamiętam'), (11, '3200'), (1, 'inny'), (7, '200'), (10, '1600'), (5, '100'), (9, '800'), (8, '400'), (12, '6400'), (3, '50'), (6, '160'), (4, '64')], default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='film_name',
            field=models.IntegerField(choices=[(2, 'Adox CMS'), (19, 'Kodak TMY'), (13, 'Ilford FP4 Plus'), (22, 'ORWO N plus'), (15, 'Ilford XP2 Super'), (0, 'nie pamiętam'), (1, 'Adox CHS'), (20, 'Kodak TRX'), (18, 'Kodak TMX'), (17, 'Kentmere'), (11, 'Ilford Pan F Plus'), (8, 'FOMA FOMAPAN R'), (6, 'FOMA FOMAPAN Creative'), (9, 'FOMA RETROPAN soft'), (10, 'FujiFilm Neopan Acros'), (12, 'Ilford HP5 Plus'), (23, 'inny'), (3, 'Adox Silvermax'), (21, 'ORWO UN'), (14, 'Ilford Delta'), (16, 'Ilford SFX '), (7, 'FOMA FOMAPAN Action'), (4, 'Film Washi W'), (5, 'FOMA FOMAPAN Classic')], default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='film_type',
            field=models.IntegerField(choices=[(2, ''), (0, 'nie pamiętam'), (1, 'inny')], default=0),
        ),
    ]
