# Generated by Django 2.1.2 on 2018-10-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SilverFox', '0002_auto_20181003_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='film_iso',
            field=models.IntegerField(choices=[(4, '64'), (5, '100'), (11, '3200'), (12, '6400'), (1, 'inny'), (0, 'nie pamiętam'), (8, '400'), (6, '160'), (10, '1600'), (9, '800'), (2, '25'), (3, '50'), (7, '200')], default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='film_name',
            field=models.IntegerField(choices=[(22, 'ORWO N plus'), (23, 'inny'), (19, 'Kodak TMY'), (0, 'nie pamiętam'), (1, 'Adox CHS'), (6, 'FOMA FOMAPAN Creative'), (14, 'Ilford Delta'), (2, 'Adox CMS'), (10, 'FujiFilm Neopan Acros'), (7, 'FOMA FOMAPAN Action'), (21, 'ORWO UN'), (18, 'Kodak TMX'), (11, 'Ilford Pan F Plus'), (8, 'FOMA FOMAPAN R'), (20, 'Kodak TRX'), (9, 'FOMA RETROPAN soft'), (17, 'Kentmere'), (5, 'FOMA FOMAPAN Classic'), (12, 'Ilford HP5 Plus'), (13, 'Ilford FP4 Plus'), (4, 'Film Washi W'), (15, 'Ilford XP2 Super'), (16, 'Ilford SFX '), (3, 'Adox Silvermax')], default=0),
        ),
    ]
